import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CalendarDays, Camera, Check, ChevronDown, Clock, Heart, Lightbulb, Mail, MapPin, Megaphone, MessageCircle, Phone, Play, Radio, ShieldCheck, Star, Target, Users, Video, Award, Zap, Eye } from 'lucide-react';


const IMG = {
  hero: '/images/AG8A5146_fullres.jpg',
  team: '/images/273A1336.JPG',
  work: '/images/6H8A9956.jpg',
  beach: '/images/AG8A4662_fullres.jpg',
  event: '/images/273A1438.JPG',
  about: '/images/273A1356.JPG',
  services: '/images/6H8A9052.jpg',
  gallery: '/images/AG8A4665_fullres.jpg',
  contact: '/images/273A1298.JPG',
  booking: '/images/273A1295.JPG',
  clients: '/images/AG8A4970_fullres.jpg',
};
const services: [string, any, string, string[]][] = [
  ['Video Production', Video, 'High-quality video content for every platform and purpose.', ['/images/273A1230.JPG', '/images/273A1232.JPG', '/images/AG8A4970_fullres.jpg', '/images/AG8A5146_fullres.jpg']],
  ['Photography', Camera, 'Capturing moments that tell your story with clarity and impact.', ['/images/AG8A4971_fullres.jpg', '/images/273A1295.JPG', '/images/273A1298.JPG', '/images/AG8A4665_fullres.jpg']],
  ['Live Streaming', Radio, 'Professional live streaming solutions for events of any scale.', ['/images/6H8A9047.jpg', '/images/6H8A9052.jpg', '/images/AG8A5146_fullres.jpg', '/images/273A1230.JPG']],
  ['Events', CalendarDays, 'End-to-end event production and management.', ['/images/273A1265.JPG', '/images/273A1438.JPG', '/images/273A1336.JPG', '/images/6H8A9050.jpg']],
  ['Marketing', Megaphone, 'Creative strategies that build brands and drive results.', ['/images/AG8A4973_fullres.jpg', '/images/AG8A4665_fullres.jpg', '/images/6H8A9956.jpg', '/images/6H8A9050.jpg']],
  ['Staging & AV', Lightbulb, 'Stage, lighting, sound and AV solutions for unforgettable events.', ['/images/6H8A9050.jpg', '/images/273A1356.JPG', '/images/273A1438.JPG', '/images/6H8A9052.jpg']],
];
type Project = {
  title: string;
  category: string;
  image: string;
  date: string;
  client: string;
  progress: number;
  status: 'Completed' | 'In Progress' | 'Planning';
  description: string;
  location: string;
};
const projects: Project[] = [
  { title:'Corporate Event Coverage', category:'Video Production', image:'/images/273A1232.JPG', date:'Mar 2026', client:'Kumul Consolidated Holdings', progress:100, status:'Completed', description:'Multi-camera coverage of the annual corporate gala, delivered as a highlight reel and full-length recording for internal and social media use.', location:'Port Moresby, NCD' },
  { title:'Documentary Production', category:'Video Production', image:'/images/273A1294.JPG', date:'Jan 2026', client:'UNDP Papua New Guinea', progress:100, status:'Completed', description:'A 25-minute documentary following community development initiatives across the Highlands, filmed over three weeks with a four-person crew.', location:'Eastern Highlands' },
  { title:'Live Conference Stream', category:'Live Streaming', image:'/images/6H8A9052.jpg', date:'Jun 2026', client:'PNG Power Limited', progress:100, status:'Completed', description:'Two-day live stream of the national energy conference with multi-camera switching, lower-thirds graphics and simultaneous upload to YouTube and Facebook.', location:'Port Moresby, NCD' },
  { title:'Brand Campaign', category:'Marketing', image:'//images/AG8A4665_fullres.jpg', date:'Feb 2026', client:'Digicel PNG', progress:100, status:'Completed', description:'A nationwide brand campaign including a 30-second TVC, six social media cutdowns and a suite of print assets rolled out across digital and out-of-home channels.', location:'Nationwide' },
  { title:'Aerial & Drone Footage', category:'Video Production', image:'/images/AG8A4970_fullres.jpg', date:'Apr 2026', client:'Santos Limited', progress:100, status:'Completed', description:'Cinematic aerial footage of project sites and surrounding landscapes captured with a licensed drone pilot, delivered as raw clips and a graded showreel.', location:'Southern Highlands' },
  { title:'Product Video Production', category:'Video Production', image:'/images/6H8A9956.jpg', date:'May 2026', client:'BSP Financial Group', progress:100, status:'Completed', description:'A series of product explainer videos for a new digital banking platform, combining live-action, motion graphics and voiceover in English and Tok Pisin.', location:'Port Moresby, NCD' },
  { title:'Community Event', category:'Events', image:'/images/273A1438.JPG', date:'Jul 2026', client:'Save the Children PNG', progress:100, status:'Completed', description:'End-to-end production of a community outreach event including stage setup, sound, live coverage and photography for post-event reporting.', location:'Morobe Province' },
  { title:'Stage & Lighting Setup', category:'Staging & AV', image:'/images/273A1356.JPG', date:'Aug 2026', client:'Air Niugini', progress:100, status:'Completed', description:'Full stage design, lighting rig and PA system for a corporate awards night attended by 400 guests, with live mixing and playback support.', location:'Port Moresby, NCD' },
  { title:'Executive Portrait Series', category:'Photography', image:'/images/AG8A4971_fullres.jpg', date:'Jul 2026', client:'Westpac PNG', progress:100, status:'Completed', description:'A studio and on-location portrait series for the executive leadership team, delivered as high-resolution retouched images for print and web.', location:'Port Moresby, NCD' },
  { title:'Mining Site Documentation', category:'Photography', image:'/images/273A1295.JPG', date:'Jun 2026', client:'Newcrest Mining', progress:100, status:'Completed', description:'Industrial photography documenting mining operations, safety procedures and community programs across multiple sites over a one-week shoot.', location:'New Ireland Province' },
  { title:'Regional Roadshow', category:'Events', image:'/images/273A1265.JPG', date:'Aug 2026', client:'ExxonMobil PNG', progress:100, status:'Completed', description:'A four-city roadshow with pop-up stage, AV and live streaming at each stop, plus daily highlight reels for social media.', location:'Multiple Provinces' },
  { title:'Tourism Promotional Video', category:'Video Production', image:'/images/AG8A4973_fullres.jpg', date:'Sep 2026', client:'PNG Tourism Promotion Authority', progress:100, status:'Completed', description:'A vibrant promotional video showcasing PNG tourism destinations, featuring aerial, cultural and landscape footage set to an original score.', location:'Nationwide' },
  { title:'Annual Report Photography', category:'Photography', image:'/images/273A1298.JPG', date:'Sep 2026', client:'The World Bank', progress:100, status:'Completed', description:'Documentary-style photography for an annual report, covering project sites, beneficiaries and stakeholder meetings across three provinces.', location:'Multiple Provinces' },
  { title:'Hydropower Project Film', category:'Video Production', image:'/images/273A1230.JPG', date:'Oct 2026', client:'JICA Papua New Guinea', progress:65, status:'In Progress', description:'An ongoing documentary project tracking the construction of a community hydropower scheme, with site visits filmed at key milestones.', location:'East New Britain' },
  { title:'National Sports Broadcast', category:'Live Streaming', image:'/images/6H8A9047.jpg', date:'Oct 2026', client:'PNG Sports Foundation', progress:40, status:'In Progress', description:'Live multi-camera streaming of a national sports tournament across three weekends, with instant replay and commentary integration.', location:'Port Moresby, NCD' },
  { title:'Cultural Festival Coverage', category:'Events', image:'/images/273A1336.JPG', date:'Nov 2026', client:'National Cultural Commission', progress:15, status:'Planning', description:'Planned coverage of a three-day cultural festival including stage production, live streaming, photography and a post-event documentary short.', location:'Eastern Highlands' },
  { title:'Digital Literacy Campaign', category:'Marketing', image:'/images/6H8A9050.jpg', date:'Nov 2026', client:'Australian High Commission', progress:20, status:'Planning', description:'A multi-channel campaign promoting digital literacy, including video assets, social content, radio spots and community workshop materials.', location:'Nationwide' },
  { title:'University Graduation Live', category:'Live Streaming', image:'/images/AG8A5146_fullres.jpg', date:'Dec 2026', client:'University of Papua New Guinea', progress:10, status:'Planning', description:'Live streaming of graduation ceremonies across two days with multi-camera setup, lower-thirds and on-demand replay for remote families.', location:'Port Moresby, NCD' },
];

function Button({to='/contact', children}:{to?:string,children:React.ReactNode}) { return <Link className="blue-btn" to={to}>{children}<ArrowRight size={17}/></Link>; }
function Stats() { return <div className="stats">{[[Users,'150+','Projects Completed'],[Heart,'100+','Happy Clients'],[CalendarDays,'10+','Years Experience'],[MapPin,'Across PNG','Serving Nationwide']].map(([Icon,n,l]:any)=><div key={l}><Icon/><b>{n}</b><span>{l}</span></div>)}</div>; }
function PageHero({eyebrow,title,copy,image=IMG.hero}:{eyebrow:string,title:React.ReactNode,copy:string,image?:string}) { return <section className="page-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.96) 0%,rgba(0,0,0,.72) 52%,rgba(0,0,0,.3)),url("${image}")`}}><div><small>// {eyebrow}</small><h1>{title}</h1><p>{copy}</p></div><i/></section>; }
function CTA(){return <section className="strip-cta"><div><b>Let's Work Together</b><span>We'd love to hear about your next project.</span></div><Button>GET IN TOUCH</Button><span><Phone/> +675 7383 0011</span><span><Mail/> info@fokalltd.com</span></section>}

export function HomePage(){
 return <><section className="home-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.96),rgba(0,0,0,.25)),url("${IMG.hero}")`}}><div className="hero-copy"><small>// WELCOME TO FOKAL SOLUTIONS LIMITED</small><h1>FOCAL POINT.<br/>REAL <em>IMPACT.</em></h1><p>We are a full-service media production, marketing and events company delivering creative solutions that connect brands with people and make an impact that lasts.</p><div className="hero-actions"><Button to="/services">OUR SERVICES</Button><Link className="outline-btn" to="/gallery">VIEW OUR WORK <ArrowRight/></Link></div></div><i/></section>
 <section className="service-ribbon">{services.map(([name,Icon,copy])=><Link to="/services" key={name}><Icon/><b>{name}</b><span>{copy}</span><ArrowRight className="mini-arrow"/></Link>)}</section>
 <section className="split-cards"><article><div><small>WHO WE ARE</small><h2>Creative Solutions.<br/>Delivered Professionally.</h2><p>Fokal Solutions Limited is a Papua New Guinea based production, marketing and events company. We combine creativity, technology and experience to deliver media and events that inspire.</p><Button to="/about">ABOUT US</Button></div><img src={IMG.team} alt="Fokal team at work"/></article><article><div><small>FEATURED WORK</small><h2>Showcasing stories.<br/>Creating impact.</h2><p>See some of our recent work across multiple industries and platforms.</p><Button to="/gallery">VIEW ALL WORK</Button></div><div className="video-tile" style={{backgroundImage:`url("${IMG.beach}")`}}><Play/></div></article></section><Stats/>

 {/* About preview */}
 <section className="home-section about-preview"><div className="about-grid"><div><small>ABOUT FOKAL SOLUTIONS</small><h2>Driven by Passion.<br/>Focused on Impact.</h2><p>Fokal Solutions Limited is a Papua New Guinea based production, marketing and events company. We are a team of creative professionals, storytellers, technicians and strategists who are passionate about delivering outstanding results.</p><p>Our mission is to connect brands with people through powerful content, meaningful experiences and innovative solutions.</p><Button to="/about">MEET THE TEAM</Button></div><img src={IMG.about} alt="Behind the scenes at Fokal Solutions"/></div>
 <div className="values"><small>OUR VALUES</small>{[[Star,'Excellence','We deliver work that exceeds expectations.'],[Users,'Commitment','We are dedicated to our clients vision.'],[ShieldCheck,'Integrity','We build trust through honest practices.'],[Heart,'Impact','We create content that resonates.']].map(([Icon,t,d]:any)=><div key={t}><Icon/><b>{t}</b><span>{d}</span></div>)}</div></section>

 {/* Services preview */}
 <section className="home-section"><div className="section-head"><small>OUR SERVICES</small><h2>Solutions that bring your vision to life.</h2><p>A full range of media production, marketing and events solutions tailored to exceed your expectations.</p></div><div className="service-grid">{services.map(([name,Icon,copy,imgs])=><article key={name}><Icon/><h3>{name}</h3><p>{copy}</p>{['Creative strategy','Professional production','Experienced team','Reliable delivery'].map(x=><span key={x}><Check/> {x}</span>)}<img src={imgs[0]} alt={name}/></article>)}</div><div className="process"><div><small>OUR PROCESS</small><h2>From Concept<br/>to Completion.</h2></div>{['Discover','Plan','Create','Deliver','Measure'].map((x,i)=><div key={x}><b>0{i+1}</b><strong>{x}</strong><span>Focused work that moves your vision forward.</span></div>)}</div><div className="section-link-row"><Button to="/services">VIEW ALL SERVICES</Button></div></section>

 {/* Gallery preview */}
 <section className="home-section"><div className="section-head"><small>OUR WORK</small><h2>Projects that speak for themselves.</h2><p>We partner with organisations across Papua New Guinea and beyond to create powerful content and memorable experiences.</p></div><div className="work-grid">{projects.slice(0,4).map((p)=><article key={p.title}><img src={p.image} alt={p.title}/><h3>{p.title}</h3><small>{p.category}</small><p>{p.description}</p></article>)}</div><div className="section-link-row"><Button to="/gallery">VIEW FULL GALLERY</Button></div></section>

 {/* Clients preview */}
 <section className="home-section clients-preview"><div className="section-head"><small>OUR CLIENTS</small><h2>Trusted by leading organisations.</h2><p>We are proud to work with a diverse range of clients across industries in Papua New Guinea and beyond.</p></div><div className="client-grid">{clientNames.slice(0,8).map((x,i)=><div key={x} className={`client-${i%4}`}>{x}</div>)}</div><div className="clients-testimonials"><blockquote>"Their professionalism and attention to detail made a huge difference in our event."<b>— Corporate Client</b></blockquote><blockquote>"A talented and reliable team that truly understands our needs."<b>— Government Partner</b></blockquote><blockquote>"Consistently provides top-quality service and creative solutions."<b>— NGO Partner</b></blockquote></div><div className="section-link-row"><Button to="/clients">VIEW ALL CLIENTS</Button></div></section>

 {/* Contact preview */}
 <section className="home-section contact-preview"><div className="contact-grid"><div><small>GET IN TOUCH</small><h2>We're here to bring your ideas to life.</h2><p>Whether you have a project in mind, need more information about our services, or just want to say hello — we'd love to hear from you.</p><div className="contact-list"><span><Phone/> <b>+675 7383 0011</b> Call or WhatsApp</span><span><Mail/><b>info@fokalltd.com</b> Send us an email</span><span><MapPin/><b>Port Moresby, NCD</b> Papua New Guinea</span></div><Button to="/contact">CONTACT US</Button></div><div className="booking-mini"><small>READY TO START?</small><h2>Get a tailored quote.</h2><p>Tell us about your project and we'll prepare a quote that fits your needs.</p><Button to="/booking">REQUEST A QUOTE</Button></div></div></section>

 <CTA/></>;
}

export function AboutPage(){return <><PageHero eyebrow="ABOUT US" title="Driven by Passion. Focused on Impact." copy="A Papua New Guinea creative company connecting brands with people through powerful content and meaningful experiences." image={IMG.about}/><main className="light-page">
<section className="about-grid"><div><small>WHO WE ARE</small><h2>Driven by Passion.<br/>Focused on Impact.</h2><p>Fokal Solutions Limited is a Papua New Guinea based production, marketing and events company. We are a team of creative professionals, storytellers, technicians and strategists who are passionate about delivering outstanding results.</p><p>Our mission is to connect brands with people through powerful content, meaningful experiences and innovative solutions.</p><Button>MEET THE TEAM</Button></div><img src={IMG.work} alt="Professional video camera"/></section>

<section className="mission-vision"><div><Target/><small>OUR MISSION</small><h3>Connecting brands with people.</h3><p>To deliver creative media, marketing and event solutions that inspire audiences, build brands and create lasting impact across Papua New Guinea and the Pacific region.</p></div><div><Eye/><small>OUR VISION</small><h3>A Pacific leader in creative media.</h3><p>To be the most trusted and innovative creative production company in Papua New Guinea, recognised for excellence, integrity and the meaningful impact of our work.</p></div></section>

<Stats/>

<section className="values"><small>OUR VALUES</small>{[[Star,'Excellence','We deliver work that exceeds expectations.'],[Users,'Commitment','We are dedicated to our clients vision.'],[ShieldCheck,'Integrity','We build trust through honest practices.'],[Heart,'Impact','We create content that resonates.']].map(([Icon,t,d]:any)=><div key={t}><Icon/><b>{t}</b><span>{d}</span></div>)}</section>

<section className="timeline"><div><small>OUR JOURNEY</small><h2>Milestones that shaped us.</h2></div><div className="timeline-track">{[['2015','Founded in Port Moresby','Fokal Solutions Limited was established with a vision to elevate creative media production in Papua New Guinea.'],['2017','Expanded services','Added live streaming and event production to our core offerings, serving clients across multiple provinces.'],['2019','National recognition','Partnered with leading organisations including Kumul Consolidated Holdings and PNG Power for major campaigns.'],['2021','Digital transformation','Embraced digital-first marketing strategies and expanded our team of creative professionals.'],['2023','Regional growth','Extended our reach across the Pacific, working with international development partners and NGOs.'],['2026','Innovation continues','Investing in cutting-edge technology and creative talent to deliver even greater impact.']].map(([year,title,desc],i)=><div className="timeline-item" key={year}><b>{year}</b><div><strong>{title}</strong><span>{desc}</span></div></div>)}</div></section>

<section className="capabilities"><div><small>WHAT WE DO</small><h2>Our capabilities.</h2><p>A full-service creative company covering every stage of production, from concept to delivery.</p></div><div className="capabilities-grid">{[[Video,'Video Production','Corporate videos, documentaries, TVCs, social content and aerial footage.'],[Camera,'Photography','Events, products, portraits and brand photography that tells your story.'],[Radio,'Live Streaming','Multi-camera live streaming for conferences, events and broadcasts.'],[CalendarDays,'Events','End-to-end event planning, production and on-site management.'],[Megaphone,'Marketing','Brand strategy, digital campaigns and content marketing that drives results.'],[Lightbulb,'Staging & AV','Stage design, lighting, sound and audiovisual solutions for any venue.']].map(([Icon,t,d]:any)=><div key={t}><Icon/><b>{t}</b><span>{d}</span></div>)}</div></section>

<section className="team-highlight"><div><small>OUR TEAM</small><h2>Creative professionals.<br/>Passionate about impact.</h2><p>Our team brings together storytellers, cinematographers, photographers, editors, producers, strategists and event specialists. We combine diverse skills with a shared commitment to delivering work that makes a difference.</p></div><div className="team-roles">{[['Producers','Project leadership and creative direction.'],['Cinematographers','Visual storytelling through every frame.'],['Editors','Post-production that brings stories to life.'],['Photographers','Capturing moments with clarity and impact.'],['Strategists','Marketing plans that connect and convert.'],['Technicians','Technical production and on-site delivery.']].map(([role,desc])=><div key={role}><b>{role}</b><span>{desc}</span></div>)}</div>
<div className="directors-section"><small>MEET OUR DIRECTORS</small><h3>Leadership with vision.</h3><div className="directors-grid">{[{name:'Director One',role:'Managing Director',bio:'With over a decade of experience in media production and creative strategy, our Managing Director leads Fokal Solutions with a passion for storytelling and a commitment to excellence across every project.'},{name:'Director Two',role:'Creative Director',bio:'Bringing a sharp creative eye and deep industry knowledge, our Creative Director shapes the artistic vision of every campaign, ensuring each piece of content resonates with audiences and delivers meaningful impact.'}].map((d)=><article key={d.name} className="director-card"><div className="director-photo"><Users/></div><div className="director-info"><b>{d.name}</b><small>{d.role}</small><p>{d.bio}</p></div></article>)}</div></div>
</section>

<section className="why-choose-us"><div><small>WHY CHOOSE US</small><h2>Reasons clients trust us.</h2></div><div className="why-grid">{[[Award,'Proven track record','150+ projects delivered across industries in PNG and the Pacific.'],[Zap,'Fast turnaround','We deliver quality work on schedule, every time.'],[ShieldCheck,'Reliable and professional','A trusted partner for organisations of every size.'],[Heart,'Local expertise','Deep understanding of PNG culture, audiences and business landscape.']].map(([Icon,t,d]:any)=><div key={t}><Icon/><b>{t}</b><span>{d}</span></div>)}</div></section>

<section className="clients-section"><div><small>OUR CLIENTS</small><h2>Trusted by leading organisations.</h2><p>We are proud to work with a diverse range of clients across industries in Papua New Guinea and beyond.</p></div><div className="client-grid">{clientNames.map((x,i)=><div key={x} className={`client-${i%4}`}>{x}</div>)}</div><div className="clients-testimonials"><blockquote>“Their professionalism and attention to detail made a huge difference in our event.”<b>— Corporate Client</b></blockquote><blockquote>“A talented and reliable team that truly understands our needs.”<b>— Government Partner</b></blockquote><blockquote>“Consistently provides top-quality service and creative solutions.”<b>— NGO Partner</b></blockquote></div></section>

</main><CTA/></>}

function ServiceThumbnail({images,alt}:{images:string[],alt:string}){
 const [idx,setIdx]=useState(0);
 useEffect(()=>{const t=setInterval(()=>setIdx(i=>(i+1)%images.length),3500);return()=>clearInterval(t);},[images.length]);
 return <div className="service-thumb-wrap">{images.map((src,i)=><img key={i} src={src} alt={alt} className={i===idx?'active':''}/>)}<div className="service-thumb-dots">{images.map((_,i)=><button key={i} className={i===idx?'active':''} onClick={()=>setIdx(i)} aria-label={`Show image ${i+1}`}/>)}</div></div>;
}
export function ServicesPage(){return <><PageHero eyebrow="OUR SERVICES" title={<>Solutions that bring<br/>your vision to life.</>} copy="A full range of media production, marketing and events solutions tailored to exceed your expectations." image={IMG.services}/><main className="light-page"><section className="service-grid">{services.map(([name,Icon,copy,imgs])=><article key={name}><Icon/><h3>{name}</h3><p>{copy}</p>{['Creative strategy','Professional production','Experienced team','Reliable delivery'].map(x=><span key={x}><Check/> {x}</span>)}<ServiceThumbnail images={imgs} alt={name}/></article>)}</section><section className="process"><div><small>OUR PROCESS</small><h2>From Concept<br/>to Completion.</h2></div>{['Discover','Plan','Create','Deliver','Measure'].map((x,i)=><div key={x}><b>0{i+1}</b><strong>{x}</strong><span>Focused work that moves your vision forward.</span></div>)}</section></main><CTA/></>}

export function GalleryPage(){
 const filters=['All','Video Production','Photography','Live Streaming','Events','Marketing','Staging & AV'];
 const [activeFilter,setActiveFilter]=useState('All');
 const [activeStatus,setStatus]=useState<'All'|'Completed'|'In Progress'|'Planning'>('All');
 const [selected,setSelected]=useState<Project|null>(null);
 const statusFilters: Array<'All'|'Completed'|'In Progress'|'Planning'>=['All','Completed','In Progress','Planning'];
 let visibleProjects=activeFilter==='All'?projects:projects.filter(p=>p.category===activeFilter);
 visibleProjects=activeStatus==='All'?visibleProjects:visibleProjects.filter(p=>p.status===activeStatus);
 const statusColor=(s:string)=>s==='Completed'?'st-complete':s==='In Progress'?'st-progress':'st-plan';
 return <><PageHero eyebrow="OUR WORK" title={<>Projects that speak<br/>for <em>themselves.</em></>} copy="We partner with organisations across Papua New Guinea and beyond to create powerful content and memorable experiences." image={IMG.gallery}/><main className="light-page"><div className="filter-bar"><div className="filters"><span className="filter-label">Category:</span>{filters.map(filter=><button key={filter} className={activeFilter===filter?'active':''} aria-pressed={activeFilter===filter} onClick={()=>setActiveFilter(filter)}>{filter}</button>)}</div><div className="filters status-filters"><span className="filter-label">Status:</span>{statusFilters.map(s=><button key={s} className={activeStatus===s?'active status-btn':'status-btn'} aria-pressed={activeStatus===s} onClick={()=>setStatus(s)}>{s}</button>)}</div></div><p className="result-count">Showing {visibleProjects.length} project{visibleProjects.length!==1?'s':''}</p><section className="work-grid work-grid-detail">{visibleProjects.map(p=><article key={p.title} className="project-card" onClick={()=>setSelected(p)}><div className="project-img-wrap"><img src={p.image} alt={p.title}/><span className={`project-status ${statusColor(p.status)}`}>{p.status}</span></div><div className="project-body"><h3>{p.title}</h3><small>{p.category}</small><div className="project-meta"><span><CalendarDays size={12}/> {p.date}</span><span><Users size={12}/> {p.client}</span><span><MapPin size={12}/> {p.location}</span></div><div className="project-progress"><div className="progress-track"><div className="progress-fill" style={{width:`${p.progress}%`}}/></div><b>{p.progress}%</b></div><p>{p.description}</p></div></article>)}</section>
 {selected && <div className="project-modal-overlay" onClick={()=>setSelected(null)}><div className="project-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>&times;</button><img src={selected.image} alt={selected.title}/><div className="modal-body"><span className={`project-status ${statusColor(selected.status)}`}>{selected.status}</span><h2>{selected.title}</h2><small>{selected.category}</small><p>{selected.description}</p><div className="modal-meta"><div><CalendarDays/><b>Date</b><span>{selected.date}</span></div><div><Users/><b>Client</b><span>{selected.client}</span></div><div><MapPin/><b>Location</b><span>{selected.location}</span></div><div><Target/><b>Progress</b><span>{selected.progress}%</span></div></div><div className="modal-progress"><div className="progress-track"><div className="progress-fill" style={{width:`${selected.progress}%`}}/></div><b>{selected.progress}% complete</b></div></div></div></div>}
 <Stats/></main><CTA/></>}
const clientNames=['KUMUL CONSOLIDATED HOLDINGS','PNG POWER','HIDES','NEWCREST','ExxonMobil','Santos','Air Niugini','Westpac','Digicel','BSP','UNDP','THE WORLD BANK','Australian Aid','JICA','Save the Children','care'];


export function ContactPage(){
 const [faqOpen,setFaqOpen]=useState<number|null>(0);
 const faqs:[string,string][]=[
  ['What services do you offer?','We offer video production, photography, live streaming, event production, marketing and staging & AV services. Whether you need a single video or a full multi-day event production, we can help.'],
  ['How do I get a quote?','Simply fill out the quote request form on our Get a Quote page with your project details, and we will prepare a tailored quote within 1-2 business days. You can also call or WhatsApp us directly.'],
  ['Do you work outside of Port Moresby?','Yes. We work with clients across all provinces of Papua New Guinea and have experience travelling to remote locations for projects. Travel and accommodation costs are included in your quote.'],
  ['Can you handle last-minute or urgent projects?','We do our best to accommodate urgent requests. Contact us directly by phone or WhatsApp for same-week bookings, and we will let you know our availability right away.'],
  ['Do you provide equipment hire only?','Yes, we offer equipment hire for cameras, lighting, sound and AV separately from our production services. Get in touch with your requirements and we will provide a hire quote.'],
  ['What formats do you deliver?','We deliver in any format you need - 4K, HD, social media cutdowns, broadcast specifications and more. Let us know your delivery requirements and we will handle the rest.'],
 ];
 const steps:[any,string,string][]=[
  [MessageCircle,'We Listen','Tell us about your project, goals and timeline. We ask the right questions to understand exactly what you need.'],
  [Target,'We Plan','We develop a tailored approach, recommend the right services and provide a clear quote with no hidden costs.'],
  [Video,'We Create','Our team gets to work - filming, designing, producing and delivering your project to the highest standard.'],
  [Check,'We Deliver','You receive your content on time and on budget, with revisions included until you are completely satisfied.'],
 ];
 const hours:[string,string,string][]=[
  ['Monday - Friday','8:00 AM - 5:00 PM','Standard business hours'],
  ['Saturday','9:00 AM - 1:00 PM','By appointment'],
  ['Sunday','Closed','Emergency enquiries via WhatsApp'],
  ['Public Holidays','Closed','Message us and we will respond next business day'],
 ];
 return <><PageHero eyebrow="CONTACT US" title={<>Let's create something<br/><em>amazing</em> together.</>} copy="We'd love to hear about your project. Fill out the form or reach out using the details below." image={IMG.contact}/>
 <main className="light-page">
  <div className="contact-grid"><section><small>GET IN TOUCH</small><h2>We're here to bring your ideas to life.</h2><p>Whether you have a project in mind, need more information about our services, or just want to say hello — we'd love to hear from you.</p><div className="contact-list"><span><Phone/> <b>+675 7383 0011</b> Call or WhatsApp</span><span><Mail/><b>info@fokalltd.com</b> Send us an email</span><span><MapPin/><b>Port Moresby, NCD</b> Papua New Guinea</span></div></section><ContactForm/></div>

  <section className="contact-extra"><div className="contact-extra-head"><small>WHY REACH OUT</small><h2>What happens after you contact us?</h2><p>We make the process simple and transparent from the very first conversation.</p></div><div className="contact-steps">{steps.map(([Icon,t,d]:any)=><div key={t}><Icon/><b>{t}</b><span>{d}</span></div>)}</div></section>

  <section className="contact-extra"><div className="contact-extra-head"><small>OFFICE HOURS</small><h2>When you can reach us.</h2><p>We're available during the hours below. For urgent enquiries outside these hours, send us a WhatsApp message and we'll respond as soon as possible.</p></div><div className="hours-grid">{hours.map(([day,time,note])=><div key={day}><b>{day}</b><span>{time}</span><small>{note}</small></div>)}</div></section>

  <section className="contact-extra"><div className="contact-extra-head"><small>FAQ</small><h2>Frequently asked questions.</h2><p>Got a question? Chances are we've answered it before. If not, send us a message and we'll get back to you.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><div key={i} className={`faq-item ${faqOpen===i?'open':''}`}><button onClick={()=>setFaqOpen(faqOpen===i?null:i)}><b>{q}</b><ChevronDown className="faq-chevron"/></button>{faqOpen===i&&<p>{a}</p>}</div>)}</div></section>
 </main></>}
function ContactForm(){return <form className="fokal-form" onSubmit={e=>e.preventDefault()}><small>SEND US A MESSAGE</small><div className="two-col"><input placeholder="Your Name *"/><input type="email" placeholder="Email Address *"/><input placeholder="Phone Number"/><select defaultValue=""><option value="" disabled>Select a Service</option>{services.map(([x])=><option key={x}>{x}</option>)}</select></div><textarea placeholder="Your Message *" rows={7}/><label><input type="checkbox"/> I agree to the privacy policy and terms of service.</label><button className="blue-btn">SEND MESSAGE <ArrowRight/></button></form>}
export function BookingPage(){return <><PageHero eyebrow="GET A QUOTE" title={<>Let's bring your<br/>vision to <em>life.</em></>} copy="Tell us about your project and we'll prepare a tailored quote that fits your needs." image={IMG.booking}/><main className="light-page quote-layout"><aside><small>HOW IT WORKS</small><h2>Simple. Fast. Effective.</h2>{['Tell Us About Your Project','We Review Your Requirements','Receive Your Quote'].map((x,i)=><div className="quote-step" key={x}><b>{i+1}</b><span><strong>{x}</strong>We'll guide you through each simple step.</span></div>)}</aside><form className="fokal-form" onSubmit={e=>e.preventDefault()}><small>REQUEST A QUOTE</small><h2>Project Details</h2><div className="two-col"><input placeholder="Full Name *"/><input placeholder="Company / Organisation *"/><input type="email" placeholder="Email Address *"/><input placeholder="Phone Number *"/></div><select defaultValue=""><option value="" disabled>Service Required *</option>{services.map(([x])=><option key={x}>{x}</option>)}</select><textarea rows={6} placeholder="Tell us about your project, goals, audience and important details..."/><label><input type="checkbox"/> I agree to the privacy policy and terms of service.</label><button className="blue-btn">SUBMIT QUOTE REQUEST <ArrowRight/></button></form></main></>}
